const MOVIES_FETCH_REQUEST  = "MOVIES_FETCH_REQUEST"
const MOVIES_FETCH_ERROR    =  "MOVIES_FETCH_ERROR"
const MOVIES_FETCH_SUCCESS  =  "MOVIES_FETCH_SUCCESS"
const SELECTED_MOVIE        =  "SELECTED_MOVIE"
const SELECTED_MOVIES_XTERS =  "SELECTED_MOVIES_XTERS"
export {
    MOVIES_FETCH_REQUEST,
    MOVIES_FETCH_ERROR,
    MOVIES_FETCH_SUCCESS,
    SELECTED_MOVIE,
    SELECTED_MOVIES_XTERS
}